---
- hosts: all

  tasks:
  - name: Get i40e version
    shell: modinfo i40e | grep '^version:' | awk '{ print $2 }'
    register: i40e_version

  - name: Update i40e to 1.3.47
    script: scripts/update-i40e.sh
    when: i40e_version.stdout != "1.3.47"
